name: Metrics
on:
  # Schedule daily updates at midnight
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual runs from the Actions tab
  workflow_dispatch:
  # Run on every push to the master/main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jose-r-morera
          template: classic
          base: header
          config_timezone: Europe/Madrid
          
          # Language Plugin Configuration
          plugin_languages: yes
          plugin_languages_ignored: makefile, jupyter notebook, html, css, tex
          plugin_languages_limit: 10
          plugin_languages_details: bytes-size, percentage
